import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Technical Documents',
      link: {
        type: 'generated-index',
        title: 'Technical Documents',
        description: 'Below is a list of technical documents that have been created by Open Infrastructure Services employees.',
        slug: '/',
      },
      items: [
        'fastapi-oidc-auth/index',
        'announcing-ncio',
        'esxi-single-usb-boot/index',
        'esxi-update-command-line/index',
      ],
    },
  ],
};

export default sidebars;
