import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Service Offerings',
      link: {
        type: 'generated-index',
        title: 'Service Offerings',
        description: "Below is a non-exhaustive list of service offerings that have been provided by Open Infrastructure Services. If you don't see a service you need, use the Contact link above to reach out to us and start a conversation.",
        slug: '/',
      },
      items: [
        {
          type: 'category',
          label: "Google Cloud Platform",
          description: "We are certified Google Cloud Partners, and have helped Google’s largest customers with their cloud migrations and digital transformation.",
          link: {
            type: 'generated-index',
            title: 'Google Cloud Platform',
            description: "Below is a list of Google Cloud Platform service offerings that have been provided by Open Infrastrucutre Services.",
            slug: '/services/google-cloud',
          },
          items: [
            // NOTE: You *DON'T* need to create a new folder and drop an
            // index.md file every time you create a new page. We were only
            // following that convention to align with our previous site layout
            // so that Google didn't complain when we cut over to the new site.
            'google-cloud/network/index',
            'google-cloud/security/index',
            'google-cloud/terraform/index',
          ],
        },
        'platform-engineering/index',
        {
          type: 'category',
          label: "Puppet",
          description: "We are world class Puppet experts ready to help your organization with Puppet modernization and migration.",
          link: {
            type: 'generated-index',
            title: 'Puppet',
            description: "Below is a list of Puppet service offerings that have been provided by Open Infrastrucutre Services.",
            slug: '/services/puppet',
          },
          items: [
            'puppet/advanced-reporting/index',
            'puppet/incremental-rollouts/index',
            'puppet/module-development/index',
            'puppet/open-source-support/index',
          ],
        },
        'vault/index',
      ],
    },
  ],
};

export default sidebars;
