---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ois-run-cert
  namespace: istio-ingress
spec:
  secretName: ois-run-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: ois.run
  dnsNames:
    - ois.run

