# NOTE: Cloudflare is in front so we use a cluster certificate.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openinfrastructure-co-cert
  namespace: istio-ingress
spec:
  secretName: openinfrastructure-co-cert
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  commonName: openinfrastructure.co
  dnsNames:
    - openinfrastructure.co
    - www.openinfrastructure.co
