resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - certificate-prd.yaml
  - certificate-stg.yaml
  - gateway-prd.yaml
  - gateway-stg.yaml
  - virtual-service-prd.yaml
  - virtual-service-stg.yaml
